### ISSUE TITLE
Do we need eslint to unify the code style?

### ISSUE THREAD

**Issue by uinz** [Lucifier129/farrow#12]
Do we need eslint to unify the code style ?

**Comment by Lucifier129** [comment]
It seems good to have eslint.

**Comment by uinz** [comment]
我们还需要完善 eslint 规则, 我们是基于社区现有的 eslint config 还是手写一份呢?

**Comment by Lucifier129** [comment]
可以选择一个跟 Farrow 当前代码风格兼容性更好的，在此基础上 override 一小部分，如何？

**Comment by uinz** [comment]
我周末找找, 如果没有我就按照之前代码的风格先输出一版

**Comment by uinz** [comment]
@Lucifier129 我按照自己的理解已经提交了一个 PR #17
