### ISSUE TITLE
How can I get the HTTP protocal version of the request in middleware?

### ISSUE THREAD

**Issue by tqma113** [Lucifier129/farrow#20]
Like 1.0, 1.1, 2.0

**Comment by Lucifier129** [comment]
Farrow provide [a hook](https://github.com/Lucifier129/farrow/blob/master/docs/http.md#usereq-incomingmessage) for this purpose

```typescript
http.use(() => {
  // original request
  let req = useReq()
  // access req.protocol
  req.protocol
})
```

For now, `farrow-http` only supports `http`.

**Comment by tqma113** [comment]
👍  THX
