### ISSUE TITLE
[Bug] can not get context after an async operation in a middleware

### ISSUE THREAD

**Issue by xialvjun** [Lucifier129/farrow#24]
This code will throw error:

```ts
http.use(async (req, next) => {
  const a = useReq();
  await delay(1000);
  const b = useReq();  // Error: Can't call useContainer out of scope, it should be placed on top of the function
  return Response.json(a === b);
});
```

The core problem is at

https://github.com/Lucifier129/farrow/blob/877d04f97ca260927483bb3db0ee7a4ef32d05a5/packages/pipeline/src/hook.ts#L29-L36 

Once `f` is an async function, only the code before the first `await` will be run in the `container scope`.

I have came up with an idea to solve this problem.
 https://github.com/Lucifier129/farrow/blob/877d04f97ca260927483bb3db0ee7a4ef32d05a5/packages/pipeline/src/pipeline.ts#L92-L102

Change all our middleware to generator function, and change the `runHooks` to a generator runner like `co`.

I'd like to draft a PR, but this will change a lot, so asking you.

**Comment by xialvjun** [comment]
It seems change `async` to `generator` is still not ok. What if the user run an `async function` in a `async function` in a `generator function` like:
```ts
async function some_async_fn() {
  const a = useReq();
  await delay(1000);
  const b = useReq();   // Error: Can't call useContainer out of scope, it should be placed on top of the function
  console.log(a === b);
}

http.use(function*(req, next) {
  const a = useReq();
  await some_async_fn();
  const b = useReq();
  return Response.json(a === b);
})
```

We need the user change all their async function to generator function. 😱 I don't know.

**Comment by xialvjun** [comment]
It seems `async_hooks` can solve this problem. https://stackabuse.com/using-async-hooks-for-request-context-handling-in-node-js/

**Comment by Lucifier129** [comment]
This is a known limitation, see [doc](https://github.com/Lucifier129/farrow#how-to-write-a-farrow-hooks).

Farrow previously has [implemented](https://github.com/Lucifier129/farrow/commit/4696fe58e0f781f2575af2acd41dae99aaff3373#diff-dc2669ef0e27412381cdc1f36fb65119ab6e912ea36b58225471ecbb8e657b37L179-L240) the hooks based on `async generator`, but it results full of `yield*`.

```typescript
pipeline.add(async function* (request, next) {
  let start = Date.now()
  let logger = yield* useLogger('time')
  let response = yield* next()

  logger.add(`path: ${request.pathname}, take time ${(Date.now() - start).toFixed(2)}ms`)

  return response
})

pipeline.add(async function* (request) {
  await sleep(500)
  return Json(request)
})
```

The current version of `farrow hooks` is simpler and easy to use, although it has some limitations.

We can use some functional techniques to overcome the problem you met.

```typescript
// a custom hooks that return async function, but itself is not async.
// It's higher-order function
function useSomeAsyncFn() {
  const a = useReq();

  return async (b) => {
       await delay(1000);
       console.log(a === b);
      return a === b
  }
}

http.use(function*(req, next) {
  // all of farrow-hooks place before the first await keyword
  const b = useReq();
  const someAsyncFn = useSomeAsyncFn()
  // call the async function returned by farrow-hooks
  const c = await someAsyncFn(b);
  return Response.json({  c });
})
```

I will look into `async_hooks` you suggested above to figure out whether it can improve farrow-hooks or not:)

**Comment by xialvjun** [comment]
`async_hooks` do solve this problem.

```ts
import Koa from "koa";
import { executionAsyncResource, createHook } from 'async_hooks';

const symbols: symbol[] = [];
function createContext<T>(value?: T) {
  const sym = Symbol('ctx');
  symbols.push(sym);
  (executionAsyncResource() as any)[sym] = value;
  return {
    get value(): T {
      return (executionAsyncResource() as any)[sym];
    },
    set value(nv: T) {
      (executionAsyncResource() as any)[sym] = nv;
    }
  }
}

createHook({
  init(asyncId, type, triggerAsyncId, resource: any) {
    const cr: any = executionAsyncResource();
    if (cr) {
      for (const sym of symbols) {
        resource[sym] = cr[sym];
      }
    }
  }
}).enable();

const app = new Koa();

const StringCtx = createContext<string>();

app.use(async (ctx, next) => {
  ctx.state.id = Math.floor(Math.random() * 1e7);
  console.log('id: ', ctx.state.id);
  await delay(1000);
  StringCtx.value = ctx.state.id;
  await next();
});

app.use(async (ctx, next) => {
  console.log('id + ctx: ', ctx.state.id, StringCtx.value);
  await delay(1000);
  console.log('id + ctx: ', ctx.state.id, StringCtx.value);
  ctx.body = ctx.state.id;
});

app.listen(4000, () => {
  console.log('4000');
});
```

Things works... 🎆

**Comment by Lucifier129** [comment]
Yes, I am working in process and it works in my local modification.

We can improve it in the next version of `farrow`

**Comment by Lucifier129** [comment]
`farrow v1.5.0` was released. 

In this version, we overcome the limitation of `farrow hooks` and refine the API of `farrow context`.

See the [doc](https://github.com/Lucifier129/farrow#how-to-write-a-farrow-hooks) for more detail:)

**Comment by xialvjun** [comment]
So fast.
