### ISSUE TITLE
文件格式的小问题

### ISSUE THREAD

**Issue by lijialiang** [Lucifier129/farrow#26]
本地环境：
- MacBook Air (M1, 2020)
- macos 11.0.1
- nodejs v14.15.1
- yarn v1.22.10

按照文档配置后，执行命令 `yarn dev` 出现报错

```sh
➜  farrow-test yarn dev
yarn run v1.22.10
$ farrow dev
env: node\r: No such file or directory
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

查询后[类似的问题](https://github.com/preactjs/preact-cli/issues/1431) 有解决方式，但希望发布 npm 包文件能修复。

**Comment by uinz** [comment]
应该可以通过配置 https://github.com/Lucifier129/farrow/blob/master/.prettierrc#L8 来避免此类问题

**Comment by Lucifier129** [comment]
还不是很明白这个问题，是 windows 系统下的编辑器的换行字符引起的问题，然后可以通过 prettier 的 endOfLine 配置来避免是吗?

endOfLine 需要设置成什么属性？

**Comment by uinz** [comment]
根据 set ff=unix 来看

应该是要把 endOfLine 配制成 lf

**Comment by lijialiang** [comment]
[这里](https://prettier.io/docs/en/options.html#end-of-line) 有较详细的配置项，`endOfLine` 配置为本来的默认值 `lf` 可以解决，应该需要重新格式化文件生效。

**Comment by Lucifier129** [comment]
我修改了 prettier 配置，并运行了格式化，然后发布了 `farrow v1.4.3` 版本，可以再试试。

不过，从 git commit [记录](https://github.com/Lucifier129/farrow/commit/4098485f1edf4ba9134e3827d7f9bd3d8693dce7)来看，没有看到 `bin` 文件里的变化，或许我本地文件已经格式化正确，但 git diff 没出来？

**Comment by lijialiang** [comment]
v1.4.3 确认已修复该问题

```
➜  farrow-test yarn dev
yarn run v1.22.10
$ farrow dev
start build
finish build in 400.00ms
```

**Comment by uinz** [comment]
挖个坟，正好看到这篇文章。
解释得还是比较详细的 https://juejin.cn/post/6844904069304156168

可能和我当初拉到 windows 上进行大量 eslint 工作有关系
