### ISSUE TITLE
Code snippets in the farrow-http document cannot pass type checking

### ISSUE THREAD

**Issue by suica** [Lucifier129/farrow#28]
Hi, I am new to farrow.

I runned code snippets of two hooks, `useBasenames ` and `usePrefix `, as provided in the [farrow-http doc](https://github.com/Lucifier129/farrow/blob/master/docs/http.md), and found out it just cannot pass the type checking.

Take `useBasenames` for example. The doc says
``` ts
const http = Http({
  basename: ['/base0'],
})
http.route('/base1', () => {
  // basenames will be ['/base0', '/base1'] if user accessed /base0/base1
  let basenames = useBasenames()
})
```
My version, which passes the type checking: 
```ts
import { Http, Response, useBasenames } from "farrow-http";

const http = Http({
  basenames: ['/base0'],
})

http.route('/base1').use((res)=>{
    let basenames = useBasenames();
    return Response.text(basenames.value.toString());
})

```
(I also add imports, in case I just import from wrong lib)

The type checker suggests that there are following issues:
1. `basenames` is mistakenly written as `basename`;
2. the usage of `route` is out of date, now its function signature is ` (name: string) => Pipeline<RequestInfo, MaybeAsyncResponse>;`;
3. the `use` method should return a response, but not `undefined`.

Maybe the doc is a little bit out of date, or I use the snippets in an incorrect way or imcompatible environments? Many thanks!

**Comment by Lucifier129** [comment]
Sorry, the documentation does not up to date.

We will update later.

**Comment by Lucifier129** [comment]
Hi, I improved the docs a little bit.

**Comment by suica** [comment]
I afraid there are still two typos and I made a PR for it. #29
