### ISSUE TITLE
Bug: farrow dev only build and exit

### ISSUE THREAD

**Issue by sinoon** [Lucifier129/farrow#32]
![image](https://user-images.githubusercontent.com/6065488/104732580-68bf6d80-5778-11eb-905b-c35373e946d2.png)

https://github.com/sinoon/repeat

**Comment by Lucifier129** [comment]
Thx feedback, I will try it later~

**Comment by sinoon** [comment]
Is very strange.

When I change dist file in farrow. and remove return whit `await builder.build()`, is fine.

![image](https://user-images.githubusercontent.com/6065488/104739311-87763200-5781-11eb-9940-663e76046e6c.png)

**Comment by Lucifier129** [comment]
The new version v0.8.32 of `esbuild`  causes the problem, now we fix the version to avoid unexpected breaking and upgrade by need.

farrow `1.5.1` solved this issue. Please try again.

**Comment by suica** [comment]
I thought it was an expected (while strange) behaviour, since the description of `npm run dev` is "for developing", which is quite vague...XD

**Comment by Lucifier129** [comment]
[esbuild v0.8.33 release](https://github.com/evanw/esbuild/releases/tag/v0.8.33)

> Fix esbuild potentially exiting early during incremental rebuilds
