### ISSUE TITLE
[Question] maybe we need session middleware or hook?

### ISSUE THREAD

**Issue by sinoon** [Lucifier129/farrow#35]
When I develop an inner service in my company. I find I need a session hook to manipulate user session and cookie.

So, considering the cors hooks are in official maintenance, maybe we need to add a session hook/middleware in the official repository?

**Comment by Lucifier129** [comment]
It may be a good idea. But for now, I am focusing on developing some more priority packages like `farrow-graphql`, `farrow-graphql-client`, `farrow-restapi`, `farrow-restapi-client` `farrow`, and so on.

Until we reach the milestone of `farrow`, it seems better to leave `farrow-session` to the community.

**Comment by tqma113** [comment]
I have worked on it and get a demo: [farrow-session](https://github.com/tqma113/farrow-session). It will be published later. And then I will make some more test and example.
