### ISSUE TITLE
Feature(http): a question about http.match

### ISSUE THREAD

**Issue by circlle** [Lucifier129/farrow#4]
## type
feature discussion
## description
```
http
  .match({
    pathname: '/product',
    query: {
      productId: Number,
    },
  }).use((request) => {
    // the type of request is detemined by the parameter of http.match
  })
```
As shown in the code above， when I use `http.match`, the type of parameter `request` is the same as the type of the parameter passing to `match`. However, when using `http.use` directly, the type of parameter `request` is `RequestInfo`. 
 
Using `http.use` directly means we can detemine the type of varialbe `request` is just `RequestInfo`, no more and no less.  What I am thinking about is **It doesn't mean we lose other fields when we make the type of some fileds more precies**. For example, when I know the pathname is `/product`, I should still known the type of `request.method` is string. 

## suggestion
- Perhaps the type of `request` should be a merge of `RequestInfo` and the more precise detail from `http.match`.
`type RequestAfterMatch = MergeType<RequestInfo, DetailFromHttpMatch>`

**Comment by Lucifier129** [comment]
A good question!

## Security Improvement

This design decision is for security concern, make the `request` in `http.match(schema).use(...)` more precise can prevent many types of Web Server Attack.

```typescript
http
  .match({
    pathname: '/product',
    query: {
      productId: Number,
    },
  }).use((request) => {
   // if merged, it's easier to encounter XSS Attack
  // request.query.xss = '</script><script>alert('xss attack')</script>'
    return Response.html(JSON.stringify(request))
  })
```

## Escape Hatch

If we get into the need of accessing original `RequestInfo` in `http.match(schema).use(...)`,  an farrow-hooks [useRequestInfo](https://github.com/Lucifier129/farrow/blob/master/docs/http.md#userequestinfo-requestinfo) will help.

```typescript
http
  .match({
    pathname: '/product',
    query: {
      productId: Number,
    },
  }).use((request) => {
   // requestInfo is the original one, and request is the precise one
   // we can calling useRequestInfo in any custom hooks
    let requestInfo = useRequestInfo()
    return Response.html(JSON.stringify(request))
  })
```

**Comment by circlle** [comment]
This kind of design is pretty good. But things can be more intesting when we choose a suitable merge strategy.

## What if we use shallow merge?

```js
http
  .match({
    pathname: '/product',
    query: {
      productId: Number,
    },
  }).use((request) => {}
)
```
the type of request will be:
```ts
type RequestAfterMatch = {
    method?: string,
    body?: any,
    headers?: RequestHeaders
    cookies?: RequestHeaders
    // pathname: string
    // query?: RequestQuery
    pathname: '/product'
    query: {
      // no xxs here
      productId: number
    }    
}
```

Now we get both security and convenience.

**Comment by Lucifier129** [comment]
Maybe we can leave these to the community,  something like `farrow-merge-router`

```typescript
import { Router } from 'farrow-merge-router'

export const router = Router()

router
  .match({
    pathname: '/product',
    query: {
      productId: Number,
    },
   })
   .use((request) => {})

```

Keep the core of Farrow simple, explicit, and predictable.
