### ISSUE TITLE
Feature request: merge query into one request like graphql

### ISSUE THREAD

**Issue by tqma113** [Lucifier129/farrow#52]
As the title.

expected
```ts
// server
...

export const entries = {
  addTodo,
  removeTodo,
}

export const service = ApiService({
  entries,
})

export const services = Router()

services.route('/api/todo').use(TodoService)

let http = Http()

http.use(services)

http.listen(3000, () => {
  console.log('server started at http://localhost:3002')
})
```

```ts
// client
import { api as TodoApi } from '../api/todo'

// `ApiMerge` need to implement
const addAndRemove = ApiMerge(TodoApi.addTodo, TodoApi.removeTodo)

const addInput = { ... }
const removeInput = { ... }

// only one request has been send
const [addResult, removeResult]= await addAndRemove(addInput, removeInput)
```

**Comment by tqma113** [comment]
client also could be this
```ts
// client
import { api as TodoApi } from '../api/todo'

// ApiMerge need to implement
const addAndRemove = ApiMerge(TodoApi.addTodo, TodoApi.removeTodo)

const addAndRemoveInput = { ... }

// only one request has been send
const [addResult, removeResult]= await addAndRemove(addAndRemoveInput)
```

**Comment by Lucifier129** [comment]
Yes, this feature is planned, it's called `batched-api`.

One way is as you suggested, another way is considered using `data-loader`

```typescript
import { api as TodoApi } from '../api/todo'

const [addResult, removeResult] = await Promise.all(
  TodoApi.addTodo(inputForAddTodo, { batched: true }),
  TodoApi.removeTodo(inputForRemoveTodo, { batched: true })
)

```

**Comment by Lucifier129** [comment]
The `batched-api` via `data-loader` is not only for the usage shown above, it can also make sense for something like `react susepnse`

```typescript
const Child = props => {
  let data = useSwr(id => Api.fetchById(id, { batched: true }), props.id, { suspend: true })
}

const Parent = props => {
  return props.list.map(item => <Child id={item.id} />)
}
```

We don't need to wrap `batched-api` into `Promise.all`.

**Comment by Lucifier129** [comment]
We can implement it in `farrow-api-client` via [dataloader](https://github.com/graphql/dataloader), and enable auto-batched by default.

- make `farrow-api-server` supports batched
- make `farrow-api-client` supports batched
- make `codegen` of `farrow-api` pass `batched: true` to each `api.invoke`

If you are interest in this feature, it's welcome for your PR:)

**Comment by tqma113** [comment]
Thansk. I don’t know how to do for now, but I’m willing to try.

**Comment by tqma113** [comment]
support batch in progress: [feat/batch](https://github.com/tqma113/farrow/tree/feat/batch)

- [x] `farrow-api-server` supports batched [9d54e4e](https://github.com/tqma113/farrow/commit/9d54e4e8e4e6bed83b28787ef25703ca79277a85)
- [x] `farrow-api-client` supports batched [03ab057](https://github.com/tqma113/farrow/commit/03ab05788f9249006e7fc614508e526b93db55e9)
- [ ] `codegen` of `farrow-api` pass batched: true to each api.invoke (in progress)
