### ISSUE TITLE
Feature Merge: farrow-deno-server

### ISSUE THREAD

**Issue by tqma113** [Lucifier129/farrow#80]
[farrow-deno-server](https://github.com/tqma113/farrow-deno-server) has been finished.

How to merge this feature into farrow?

**Comment by Lucifier129** [comment]
It seems like `farrow-deno-server` was already a standalone package in npm, does it need to merge into farrow repos?

Or we can add `farrow-deno-server` to `Community Packages` in [here](https://github.com/Lucifier129/farrow/blob/master/docs/index.md#community-packages)

I don't know. 

How do you think?

**Comment by tqma113** [comment]
I prefer to merge it into farrow. I will unpublish farrow-deno-server npm package.

**Comment by tqma113** [comment]
Another point need to focus is the `codegen` module in `farrow-deno-server` maybe not good enough.

`codegen` in farrow-api is base on `farrow-pipeline`. But in `farrow-deno-server` is just simple request sending.

Can you give me some opinions?

**Comment by Lucifier129** [comment]
Current naive implemation of `codegen` missing interception and batching, if we want more features, we need to implement `farrow-pipeline` and `dataloader` in `deno`.

I am struggling whether we should perform a full-features re-implement Farrow in deno, it can solve all problems now we met. There will be a huge work that needs to do.

Maybe it depends on what do you use `farrow-deno-server` for?

**Comment by Lucifier129** [comment]
> I prefer to merge it into farrow. I will unpublish farrow-deno-server npm package.

You can add `packages/farrow-deno-server` and move the code in it

**Comment by Lucifier129** [comment]
Shall we rename `farrow-deno-server` to `farrow-deno-api`?

**Comment by tqma113** [comment]
#82

**Comment by tqma113** [comment]
Unpublish farrow-deno-server is done.

**Comment by Lucifier129** [comment]
`farrow-deno-api` was published to npm
