### ISSUE TITLE
http.serve serve static assets, but not go next when the file is not exist.

### ISSUE THREAD

**Issue by tqma113** [Lucifier129/farrow#9]
## Type
feature request or bug report.

## Module
farrow-http -> http.serve

## Current
when the file is not exist return then 500 error.

## Expect
when the file is not exist go down to next handler.

demo: 
```ts
http.serve("/", "./static");

http.use(async (req) => {
  const url = req.pathname;
  const html = await render(url);
  const str = ReactDOMServer.renderToString(html);

  return Response.html("<!DOCTYPE html>" + str);
});
```
In above demo, when request not match in `http.serve("/", "./static")` expect it go down to then page render handler.

**Comment by Lucifier129** [comment]
Waiting for your PR:)
